# Generated by Django 4.1.3 on 2022-11-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0002_rename_timestamp_file_created_at_file_script_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GentleJson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", models.FileField(upload_to="json/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applipsync.file",
                    ),
                ),
            ],
        ),
    ]
