# Generated by Django 4.1.3 on 2022-11-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0003_gentlejson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gentlejson",
            name="json",
        ),
    ]
