# Generated by Django 4.1.3 on 2022-11-29 05:04

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0006_alter_gentlejson_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_frame", jsonfield.fields.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gentle_josn",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applipsync.gentlejson",
                    ),
                ),
            ],
        ),
    ]
