# Generated by Django 4.1.3 on 2022-11-29 07:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applipsync', '0007_videoframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoframe',
            name='video_frame_keys',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
