# Generated by Django 4.1.3 on 2022-12-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0009_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="remark",
        ),
        migrations.AddField(
            model_name="file",
            name="host",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
