# Generated by Django 4.1.3 on 2022-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0010_remove_file_remark_file_host_file_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mouth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
