# Generated by Django 4.1.3 on 2022-12-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0011_mouth"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="mouth",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applipsync.mouth",
            ),
        ),
    ]
