# Generated by Django 4.1.3 on 2022-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0013_mouth_a_e_h"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouth",
            name="d_j_ch_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="f_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="l_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="m_b_close_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="o_big_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="o_small_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="oh_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="th_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouth",
            name="trans_h",
            field=models.FileField(default=1, upload_to="images/test_normal/"),
            preserve_default=False,
        ),
    ]
