# Generated by Django 4.1.3 on 2022-12-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applipsync",
            "0014_mouth_d_j_ch_h_mouth_f_h_mouth_l_h_mouth_m_b_close_h_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouth",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
