# Generated by Django 4.1.3 on 2022-12-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipsync", "0015_alter_mouth_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="slug",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
